repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: golangci-lint
        args:
          - -E
          - gocritic
          - -E
          - errorlint
          - -E
          - bodyclose
          - -E
          - gosec
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: go-mod-tidy